#!/bin/bash

# Sort Files
perl util/sort-Xcode-project-file SudoEntitlements.xcodeproj/project.pbxproj

if [[ `git status --porcelain` ]]; then
    echo "please run 'perl util/sort-xcode-project-file SudoEntitlements.xcodeproj/project.pbxproj' locally and commit again"
    exit 1
fi
